ZSH_THEME_GIT_PROMPT_PREFIX="%{%F{15}%}["
ZSH_THEME_GIT_PROMPT_SUFFIX="%{%F{15}%}]%{$reset_color%} "

ZSH_THEME_GIT_PROMPT_EQUAL_REMOTE="%{%F{12}%}"      # blue
ZSH_THEME_GIT_PROMPT_AHEAD_REMOTE="%{%F{10}%}"      # green
ZSH_THEME_GIT_PROMPT_BEHIND_REMOTE="%{%F{9}%}"      # red
ZSH_THEME_GIT_PROMPT_DIVERGED_REMOTE="%{%F{11}%}"   # yellow
ZSH_THEME_GIT_PROMPT_NO_REMOTE="%{%F{6}%}"          # teal

ZSH_THEME_GIT_PROMPT_INDEX_PREFIX="%{%F{10}%}"
ZSH_THEME_GIT_PROMPT_INDEX_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_WORKING_PREFIX="%{%F{9}%}"
ZSH_THEME_GIT_PROMPT_WORKING_SUFFIX="%{$reset_color%}"
