#!/bin/sh
git_status="$(git -c color.status=false status --short --branch 2> /dev/null)"

file_pattern="^([^#])(.) (.*)$"

dirty=0
#linecount=0
while IFS= read -r line
do
  #echo "$line"
  #linecount=$((linecount + 1))
  if [[ $line =~ $file_pattern ]]; then
    dirty=1
  fi
done <<< "$git_status"

#echo "$linecount line(s)"
echo "Dirty: $dirty"

